development:
  encoding: unicode
  adapter: postgresql
  pool: 5
  database: whatsapp_ai_assistant_development
test:
  encoding: unicode
  adapter: postgresql
  pool: 5
  database: whatsapp_ai_assistant_test
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
